name: masterchess
description: A brief description of your package.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Updated SDK constraint
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  chess: ^0.7.0
  chess_vectors_flutter: ^1.1.0
  flutter:
    sdk: flutter
  flutter_chess_board: ^1.0.1
  flutter_tts: ^3.8.5
  http: ^0.13.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true